on:
  push:
    branches: [ "github-pages" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: false
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4